// <auto-generated />
using System;
using LogTailer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogTailer.Data.Migrations
{
    [DbContext(typeof(LogTailerContext))]
    partial class LogTailerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("LogTailer.Domain.Models.LineHighlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackgroundColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForegroundColor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRegex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchString")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("LineHighlights");
                });

            modelBuilder.Entity("LogTailer.Domain.Models.OpenFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("OpenFiles");
                });

            modelBuilder.Entity("LogTailer.Domain.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("LogTailer.Domain.Models.LineHighlight", b =>
                {
                    b.HasOne("LogTailer.Domain.Models.Session", null)
                        .WithMany("LineHighlights")
                        .HasForeignKey("SessionId");
                });

            modelBuilder.Entity("LogTailer.Domain.Models.OpenFile", b =>
                {
                    b.HasOne("LogTailer.Domain.Models.Session", null)
                        .WithMany("OpenFiles")
                        .HasForeignKey("SessionId");
                });

            modelBuilder.Entity("LogTailer.Domain.Models.Session", b =>
                {
                    b.Navigation("LineHighlights");

                    b.Navigation("OpenFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
